import torch
from torch import Tensor


torch.backends.cudnn.benchmark = True


TAU_EPS = 1.0e-6


def factorized_arrival_time(tau: Tensor, pair_coords: Tensor, dim: int) -> Tensor:
    """Return paper Eq. 5: ``T = log(tau)^2 ||q0 - q1||``.

    ``tau`` is generated by a sigmoid network, but clamping avoids numerical
    infinities after checkpoint loading or mixed-precision inference.  The
    Euclidean norm intentionally has no additive epsilon: coincident start and
    goal configurations must have zero arrival time.
    """

    if tau.ndim == 1:
        tau = tau[:, None]
    if pair_coords.ndim != 2 or pair_coords.shape[1] != 2 * int(dim):
        raise ValueError(
            f"Expected pair coordinates [N,{2 * int(dim)}], got {tuple(pair_coords.shape)}"
        )
    tau_safe = torch.clamp(tau, min=TAU_EPS, max=1.0 - TAU_EPS)
    q_delta = pair_coords[:, :dim] - pair_coords[:, dim:]
    pair_distance = torch.linalg.vector_norm(q_delta, dim=1, keepdim=True)
    return torch.square(torch.log(tau_safe)) * pair_distance


class Function:
    def __init__(self, path: str, device: str, network, dim: int):
        self.path = path
        self.device = device
        self.network = network
        self.dim = dim
        self.total_train_loss = []
        self.total_val_loss = []
        self.alpha = 1.025
        limit = 0.5
        self.margin = limit / 15.0
        self.offset = self.margin / 10.0
        self.td_loss_weight = 1.0e-3
        self.speed_loss_weight = 1.0e-2
        self.log_speed_loss_weight = 0.0
        self.direct_speed_loss_weight = 0.0
        self.normal_loss_weight = 1.0e-3
        self.normal_cos_loss_weight = 0.0
        self.near_obstacle_loss_weight = 0.0
        self.low_speed_threshold = 0.20
        self.low_speed_pred_max = 0.35
        self.low_speed_penalty_weight = 0.0
        self.effective_speed_floor = 0.05

    def gradient(self, y: Tensor, x: Tensor, create_graph: bool = True) -> Tensor:
        return torch.autograd.grad(
            y,
            x,
            torch.ones_like(y),
            only_inputs=True,
            retain_graph=True,
            create_graph=create_graph,
        )[0]

    def arrival_time(self, tau: Tensor, pair_coords: Tensor) -> Tensor:
        return factorized_arrival_time(tau, pair_coords, self.dim)

    def _arrival_with_gradient(self, Xp: Tensor, create_graph: bool = True) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        tau, _w, mapped_coords = self.network.out(Xp)
        arrival_time = self.arrival_time(tau, mapped_coords)
        dtime = self.gradient(arrival_time, mapped_coords, create_graph=create_graph)
        return arrival_time, tau, dtime, mapped_coords

    @staticmethod
    def _speed_from_time_gradient(dtime: Tensor, dim: int) -> tuple[Tensor, Tensor]:
        dt0 = dtime[:, :dim]
        dt1 = dtime[:, dim:]
        s0 = torch.einsum("ij,ij->i", dt0, dt0)
        s1 = torch.einsum("ij,ij->i", dt1, dt1)
        return torch.rsqrt(s0 + 1.0e-8), torch.rsqrt(s1 + 1.0e-8)

    def TravelTimes(self, Xp: Tensor) -> Tensor:
        tau, _w, mapped_coords = self.network.out(Xp)
        return self.arrival_time(tau, mapped_coords)[:, 0]

    def Speed(self, Xp: Tensor) -> Tensor:
        _arrival, _tau, dtime, _mapped_coords = self._arrival_with_gradient(Xp, create_graph=False)
        speed0, _speed1 = self._speed_from_time_gradient(dtime, self.dim)
        return speed0

    def Gradient(self, Xp: Tensor) -> Tensor:
        """Return Eq. 11's descent vector ``-S^2 grad(T)`` at both ends."""

        _arrival, _tau, dtime, _mapped_coords = self._arrival_with_gradient(Xp, create_graph=False)
        dt0 = dtime[:, : self.dim]
        dt1 = dtime[:, self.dim :]
        denom0 = torch.sum(dt0 * dt0, dim=1, keepdim=True).clamp_min(1.0e-8)
        denom1 = torch.sum(dt1 * dt1, dim=1, keepdim=True).clamp_min(1.0e-8)
        return torch.cat((-dt0 / denom0, -dt1 / denom1), dim=1)

    def Loss(self, points: Tensor, Yobs: Tensor, normal: Tensor, beta: float, gamma: float, epoch: int):
        del gamma, epoch
        n = Yobs.shape[0]
        arrival_time, _tau, dtime, Xp = self._arrival_with_gradient(points, create_graph=True)
        target_speed = torch.clamp(Yobs, min=0.0, max=1.0)
        yobs_safe = torch.clamp(
            target_speed,
            min=float(getattr(self, "effective_speed_floor", 0.05)),
            max=1.0,
        )

        dt0 = dtime[:, : self.dim]
        dt1 = dtime[:, self.dim :]
        grad_norm_sq0 = torch.einsum("ij,ij->i", dt0, dt0)
        grad_norm_sq1 = torch.einsum("ij,ij->i", dt1, dt1)

        td_weight = float(getattr(self, "td_loss_weight", 1.0e-3))
        with torch.no_grad():
            length0 = 0.03 / yobs_safe[:, 0].unsqueeze(1)
            dir0 = length0 * (dt0 * yobs_safe[:, 0].unsqueeze(1) ** 2)
            Xpnew0 = Xp.clone().detach()
            Xpnew0[:, : self.dim] = Xpnew0[:, : self.dim] - dir0
            tau_new0, _w, mapped_new0 = self.network.out(Xpnew0)
            time_new0 = self.arrival_time(tau_new0, mapped_new0)

            length1 = 0.03 / yobs_safe[:, 1].unsqueeze(1)
            dir1 = length1 * (dt1 * yobs_safe[:, 1].unsqueeze(1) ** 2)
            Xpnew1 = Xp.clone().detach()
            Xpnew1[:, self.dim :] = Xpnew1[:, self.dim :] - dir1
            tau_new1, _w, mapped_new1 = self.network.out(Xpnew1)
            time_new1 = self.arrival_time(tau_new1, mapped_new1)

        tau_loss0 = td_weight * ((arrival_time - time_new0 - length0) ** 2).squeeze()
        tau_loss1 = td_weight * ((arrival_time - time_new1 - length1) ** 2).squeeze()
        tau_loss0[arrival_time[:, 0] <= length0.squeeze()] = 0.0
        tau_loss1[arrival_time[:, 0] <= length1.squeeze()] = 0.0
        tau_loss = tau_loss0 + tau_loss1

        # Eq. 12: (sqrt(S* / S) - 1)^2, with S = 1 / ||grad(T)||.
        grad_norm0 = torch.sqrt(grad_norm_sq0 + 1.0e-8)
        grad_norm1 = torch.sqrt(grad_norm_sq1 + 1.0e-8)
        loss_weight = float(getattr(self, "speed_loss_weight", 1.0e-2))
        near_weight = float(getattr(self, "near_obstacle_loss_weight", 0.0))
        risk0 = 1.0 + near_weight * (1.0 - target_speed[:, 0]) ** 2
        risk1 = 1.0 + near_weight * (1.0 - target_speed[:, 1]) ** 2
        loss0 = loss_weight * risk0 * (torch.sqrt(yobs_safe[:, 0] * grad_norm0) - 1.0) ** 2
        loss1 = loss_weight * risk1 * (torch.sqrt(yobs_safe[:, 1] * grad_norm1) - 1.0) ** 2

        pred_speed0 = torch.rsqrt(grad_norm_sq0 + 1.0e-8)
        pred_speed1 = torch.rsqrt(grad_norm_sq1 + 1.0e-8)
        # A bounded-gradient multiplicative speed residual. Eq. 12 becomes
        # weak for small target speeds, allowing free-space samples to reduce
        # average loss while obstacle speeds remain inverted. Smooth-L1 in
        # log-speed space gives equal importance to relative errors at 0.1
        # and 1.0 without the unbounded raw-speed MSE used previously.
        log_speed_weight = float(getattr(self, "log_speed_loss_weight", 0.0))
        if log_speed_weight > 0.0:
            log_pred0 = -0.5 * torch.log(grad_norm_sq0 + 1.0e-4)
            log_pred1 = -0.5 * torch.log(grad_norm_sq1 + 1.0e-4)
            log_target0 = torch.log(yobs_safe[:, 0])
            log_target1 = torch.log(yobs_safe[:, 1])
            log_err0 = torch.nn.functional.smooth_l1_loss(
                log_pred0, log_target0, reduction="none", beta=0.5
            )
            log_err1 = torch.nn.functional.smooth_l1_loss(
                log_pred1, log_target1, reduction="none", beta=0.5
            )
            loss0 = loss0 + log_speed_weight * log_err0
            loss1 = loss1 + log_speed_weight * log_err1
        direct_speed_weight = float(getattr(self, "direct_speed_loss_weight", 0.0))
        if direct_speed_weight > 0.0:
            loss0 = loss0 + direct_speed_weight * risk0 * (pred_speed0 - target_speed[:, 0]) ** 2
            loss1 = loss1 + direct_speed_weight * risk1 * (pred_speed1 - target_speed[:, 1]) ** 2

        low_threshold = float(getattr(self, "low_speed_threshold", 0.20))
        low_pred_max = float(getattr(self, "low_speed_pred_max", 0.35))
        low_penalty = float(getattr(self, "low_speed_penalty_weight", 0.0))
        if low_penalty > 0.0 and low_threshold > 0.0:
            low0 = (target_speed[:, 0] <= low_threshold).float()
            low1 = (target_speed[:, 1] <= low_threshold).float()
            loss0 = loss0 + low_penalty * low0 * torch.relu(pred_speed0 - low_pred_max) ** 2
            loss1 = loss1 + low_penalty * low1 * torch.relu(pred_speed1 - low_pred_max) ** 2
        diff = loss0 + loss1

        normal_weight = float(getattr(self, "normal_loss_weight", 1.0e-3))
        normal0 = normal[:, : self.dim]
        normal1 = normal[:, self.dim :]
        n_risk0 = (1.0 + near_weight * (1.0 - target_speed[:, 0]) ** 2).unsqueeze(1)
        n_risk1 = (1.0 + near_weight * (1.0 - target_speed[:, 1]) ** 2).unsqueeze(1)
        n_loss0 = n_risk0 * (1.001 - yobs_safe[:, 0].unsqueeze(1)) * (
            yobs_safe[:, 0].unsqueeze(1) * dt0 + normal0
        ) ** 2
        n_loss1 = n_risk1 * (1.001 - yobs_safe[:, 1].unsqueeze(1)) * (
            yobs_safe[:, 1].unsqueeze(1) * dt1 + normal1
        ) ** 2
        n_loss = normal_weight * (torch.sum(n_loss0, dim=1) + torch.sum(n_loss1, dim=1))

        normal_cos_weight = float(getattr(self, "normal_cos_loss_weight", 0.0))
        if normal_cos_weight > 0.0:
            dt0_dir = -dt0 / torch.clamp(torch.linalg.norm(dt0, dim=1, keepdim=True), min=1.0e-8)
            dt1_dir = -dt1 / torch.clamp(torch.linalg.norm(dt1, dim=1, keepdim=True), min=1.0e-8)
            cos0 = torch.sum(dt0_dir * normal0, dim=1)
            cos1 = torch.sum(dt1_dir * normal1, dim=1)
            near0 = (1.0 - target_speed[:, 0]) ** 2
            near1 = (1.0 - target_speed[:, 1]) ** 2
            n_loss = n_loss + normal_cos_weight * (
                near0 * (1.0 - cos0) ** 2 + near1 * (1.0 - cos1) ** 2
            )

        exp_arg = torch.clamp(-0.15 * arrival_time[:, 0], min=-20.0, max=20.0)
        sample_weight = torch.exp(exp_arg)
        lossn = torch.sum((diff + n_loss + tau_loss) * sample_weight) / n
        return beta * lossn, lossn, diff


def verify_factorized_time_gradients() -> dict[str, float]:
    """Small autograd/finite-difference check for Eq. 5 and its gradients.

    Run with ``python -m ur_mntfields_arm.tb_core.model_function_metric``.
    This is intentionally independent of ROS, checkpoints, and CUDA.
    """

    dim = 3
    coords = torch.tensor(
        [[0.21, -0.33, 0.14, -0.18, 0.11, -0.27]], dtype=torch.float64, requires_grad=True
    )

    def tau_for(x: Tensor) -> Tensor:
        delta = x[:, :dim] - x[:, dim:]
        return torch.sigmoid(-0.35 + 0.22 * torch.sum(delta * delta, dim=1, keepdim=True))

    arrival = factorized_arrival_time(tau_for(coords), coords, dim)
    analytic = torch.autograd.grad(arrival.sum(), coords)[0]
    finite = torch.zeros_like(coords)
    step = 1.0e-6
    with torch.no_grad():
        for axis in range(coords.shape[1]):
            plus = coords.detach().clone()
            minus = coords.detach().clone()
            plus[0, axis] += step
            minus[0, axis] -= step
            finite[0, axis] = (factorized_arrival_time(tau_for(plus), plus, dim)[0, 0] - factorized_arrival_time(tau_for(minus), minus, dim)[0, 0]) / (2.0 * step)

        swapped = torch.cat((coords.detach()[:, dim:], coords.detach()[:, :dim]), dim=1)
        symmetric_error = torch.max(
            torch.abs(factorized_arrival_time(tau_for(coords.detach()), coords.detach(), dim) - factorized_arrival_time(tau_for(swapped), swapped, dim))
        ).item()
        coincident = torch.zeros((1, 2 * dim), dtype=torch.float64)
        zero_time_error = torch.abs(factorized_arrival_time(tau_for(coincident), coincident, dim)).max().item()
    max_gradient_error = torch.max(torch.abs(analytic - finite)).item()
    if max_gradient_error > 2.0e-6 or symmetric_error > 1.0e-12 or zero_time_error > 1.0e-12:
        raise AssertionError(
            "Factorized arrival-time verification failed: "
            f"gradient={max_gradient_error:.3e}, symmetry={symmetric_error:.3e}, zero={zero_time_error:.3e}"
        )
    return {
        "max_gradient_error": float(max_gradient_error),
        "symmetric_error": float(symmetric_error),
        "zero_time_error": float(zero_time_error),
    }


if __name__ == "__main__":
    print(verify_factorized_time_gradients())
